// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller.coffee.erb"
application.register("form", FormController)

import MenuController from "./menu_controller.coffee.erb"
application.register("menu", MenuController)

import MessageController from "./message_controller.coffee.erb"
application.register("message", MessageController)

import ModalController from "./modal_controller.coffee.erb"
application.register("modal", ModalController)

import { AttachmentUpload } from "@rails/actiontext/app/javascript/actiontext/attachment_upload"

addEventListener("trix-attachment-add", event => {
  const { attachment, target } = event

  if (attachment.file) {
    const upload = new AttachmentUpload(attachment, target)
    upload.start()
  }
})