// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { AttachmentUpload } from "@rails/actiontext/app/javascript/actiontext/attachment_upload"

import controllers from "./**/*_controller.js"
controllers.forEach((controller) => {
  application.register(controller.name, controller.module.default)
})

addEventListener("trix-attachment-add", event => {
  const { attachment, target } = event
  if (attachment.file) {
    const upload = new AttachmentUpload(attachment, target)
    upload.start()
  }
})