default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5

development:
  <<: *default
  database: domando_development
  username: postgres
  password: qwerty
  host: localhost
  sslmode: prefer

test:
  <<: *default
  database: domando_test
  username: postgres
  password: qwerty
  host: localhost
  sslmode: prefer

production:
  <<: *default
  database: <%= Settings.database.production.database %>
  username: <%= Settings.database.production.username %>
  password: <%= Rails.application.credentials.production_db_password %>
  host: <%= Settings.database.production.host %>
  sslmode: <%= Settings.database.production.sslmode %>
