default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5

development:
  <<: *default
  database: domando_development
  username: postgres
  password: qwerty
  host: localhost
  sslmode: prefer

test:
  <<: *default
  database: domando_test
  username: postgres
  password: qwerty
  host: localhost
  sslmode: prefer

production:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database_url %>
  sslmode: <%= Settings.database.production.sslmode %>
